POST http://localhost:4000/event/organizers HTTP/1.1

Content-Type: application/json
{
 	"firstname": "Jean Claude",
 	"lastname":"Mugenzi",
    "email": "jean123@gmail.com",
    "password": "123"
}

#################################################

GET http://localhost:4000/event/organizers

#################################################
GET http://localhost:4000/event/organizers/habibu@gmail.com


{
    "email": "mugenzi1@gmail.com",
    "password": "123"
}

###
POST http://localhost:4000/event/authentication/login HTTP/1.1
//content-type: application/json 

{
    "email": "mugenzi1@gmail.com",
    "password": "123"
}
###

GET http://localhost:4000/event/organizers/logged HTTP/1.1

'x-access-token':  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdG5hbWUiOiJKYW52aWVyIiwibGFzdG5hbWUiOiJJc2FiYW5lIiwiZW1haWwiOiJpc2FiYW5lampAZ21haWwuY29tIiwiaWF0IjoxNTg0NDU5ODA2LCJleHAiOjE1ODQ1NDYyMDZ9.EidaZy2NSCsES-fhHR4mr7uzZVnqtQ71nnYrRHSSbQ8" 