

GET http://localhost:4000/events HTTP/1.1

#################################################

POST http://localhost:4000/events/create HTTP/1.1
Content-Type: application/json

{
   "name": "Test Event 5",
   "eventDate": "Test Event 5",
   "eventType": "Test Event 5",
   "eventStatus": "Test Event 5",
   "eventVenue": {
       "location": {
           "lat": "Test Event 5",
           "long": "Test Event 5"
       },
       "address": {
         "street": "Test Event 5",
           "city": "Test Event 5",
           "state": "Test Event 5",
           "zipcode":"Test Event 5"
       }
   }
}



############################

GET http://localhost:4000/guests/test


#################################################

POST http://localhost:4000/guests/create/5e70432ae91fec2f14f7f48a HTTP/1.1
Content-Type: application/json

{
   "firstname": "Test Guest",
   "lastname": "Test Guest",
   "email": "Test Guest",
   "phone": "Test Guest",
   "status": "Test Guest" 
}


######################################################
GET http://localhost:4000/guests HTTP/1.1







#################################################

PUT http://localhost:4000/events/update/5e70432ae91fec2f14f7f48a HTTP/1.1
Content-Type: application/json

{
   "name": "Event Test",
   "eventDate": "Event Test",
   "eventType": "Event Test",
   "eventStatus": "Event Test",
   "eventVenue": {
       "location": {
           "lat": "Event Test0",
           "long": "Event Test0"
       },
       "address": {
         "street": "Event Test0",
           "city": "Fairfield",
           "state": "IA",
           "zipcode":"52557"
       }
   }
}
