GET http://localhost:4000/ HTTP/1.1

###
GET http://localhost:4000/3 HTTP/1.1

 
####
POST http://localhost:4000 HTTP/1.1
content-type: application/json

{
   "eventName":"Mugenzi & Fabric",
   "eventType":"Marriage",
   "eventDate":"2020-01-01",
   "eventStatus":"Pending",
   "guest":{
          "guestName":"Emino Janvier",
          "telephone": 6418191101,
          "guestEmail":"isabanej@gmail.com"},
   "organizer":{
            "organizer":"Mugenzi Jean",
            "username":"Mugenzi",
            "password":"mugenzi123",
            "email":"mugenzi@gmail.com"},
   "address": {
       "city":"Fairfield",
       "state":"IOWA",
       "ZIP":52557,
       "street":"1000 N 4TH ST"},
    "service":{
        "serviceName": "Food",
        "serviceType": "Vegeterian",
        "serviceStatus": "available" 
    } 
} 



 